### ISSUE TITLE
Exception `TypeError: Cannot read properties of undefined (reading 'port')` thrown when ending session

### ISSUE THREAD

**Issue by manubo** [zikaari/webext-bridge#40]
Hi, I am using the next-version of this package. Each time I reload the browser page, i.e. the session is ended, an exception is raised in the background script: 

```
Error in event handler: TypeError: Cannot read properties of undefined (reading 'port')
    at Object.aboutSessionEnded (<URL>)
    .
    .
    .
``` 

The exception is thrown in `aboutSessionEnded`. Both variables `conn` and `fingerprint` are `undefined`, which results in a `true` evaluation of the condition and then it tries to read `conn.port`, which causes the error:

```
aboutSessionEnded: (endedSessionFingerprint) => {
        const conn = connMap.get(endpoint);
        if ((conn == null ? void 0 : conn.fingerprint) === fingerprint) {
          PortMessage.toExtensionContext(conn.port, {
            status: "terminated",
            fingerprint: endedSessionFingerprint
          });
        }
        return nextChain(notifications);
      }
```

The rogue message is a message sent from the background and its `rogueMessage.from.fingerprint` is undefined.

Not sure if I am doing something wrong or how to fix this. Anybody else having the same issue? Any help would be highly appreciated, thanks.

**Comment by zikaari** [comment]
@manubo Please verify again if `webext-bridge@6.0.0-rc4` fixes this, and close this issue if it does. Thank you!
