### ISSUE TITLE
Sending message from popup to background crashed (Cannot read properties of undefined reading fingerprint)

### ISSUE THREAD

**Issue by devnomic** [zikaari/webext-bridge#57]
**Case:**

In `background` script create multiple popup  with `url` to popup extension url
````
const url = chrome.runtime.getURL('popup.html') + '/say-hello';

await chrome.windows.create({
    type: 'popup',
    url,
    focused: true,
    top: 100,
    left: 100,
    width: 400,
    height: 400,
  });

await chrome.windows.create({
    type: 'popup',
    url,
    focused: true,
    top: 100,
    left: 100,
    width: 400,
    height: 400,
  });

onMessage('hello', ({data}) => {
  console.log(data);
});
````

In the `popup` window there is a button, when this button clicked it will send message to background.
```
await sendMessage('hello', { name: 'Bob' }, 'background');
```
**Expected result**

Since there is 2 windows created, in both windows when the button is clicked, `background` script should print console log with the data twice.

**Problem / Bug**

`background` script only print one console log, the other one crashed when the button inside the `popup` window is clicked.
The last created window, indeed successfully send the message to background and print log to console. In another window, when the button is clicked  `webext` will crash.

**Error preview**
<img width="800" alt="Screenshot 2023-04-27 at 08 21 00" src="https://user-images.githubusercontent.com/101681592/234738610-103deb0e-8920-446e-9fcc-b86641e6fc37.png">

<img width="353" alt="Screenshot 2023-04-27 at 08 21 13" src="https://user-images.githubusercontent.com/101681592/234738685-741e6ced-a41e-45ab-9301-f9878b1d4073.png">

**Comment by farazshuja** [comment]
How you are importing sendMessage? You need to import it from 'webext-bridge/background` or `webext-bridge/content-script` based on the base you are.

**Comment by zikaari** [comment]
@jnarowski You need to specify a destination
@devnomic Can you try `6.0.1`? There are important fixes there like https://github.com/zikaari/webext-bridge/commit/959fb700110defc8c11ecdf3c3d8e2532ce6a78c

**Comment by code4you2021** [comment]
@zikaari 

+1

version:6.0.1

I have the same problem.

---

<img width="690" alt="CleanShot 2023-10-18 at 18 29 17@2x" src="https://github.com/zikaari/webext-bridge/assets/83153991/9d028d54-9280-4262-bfb3-99733be6a214">

<img width="638" alt="CleanShot 2023-10-18 at 18 31 10@2x" src="https://github.com/zikaari/webext-bridge/assets/83153991/9f347735-7ea5-4f46-a3e2-30e3f54d71e7">

---

background.js
```javascript
import { sendMessage } from "webext-bridge/background";

sendMessage("background", {
    id: browser.runtime.id,
    message: "Hello from background!",
});
```

content-script.js
```javascript
import { onMessage } from "webext-bridge/content-script";

onMessage("background", (data) => {
    console.log("from background", data);
});
```

**Comment by devnomic** [comment]
Sorry, i have use another lib, lets just close this issue, maybe already fixed.

**Comment by amduenas07** [comment]
I'm having the same problem using v6.0.1, I'm importing from '*/background'. Any help?

**Comment by solastley** [comment]
@zikaari same exact problem here, unfortunately the library seems to be completely unusable because of this bug

**Comment by myjustify** [comment]
@devnomic 
Hello, may I ask what library it has been changed to.
The problem still seems to exist 🤣
