### ISSUE TITLE
[Bug] `DataTypeKey` not working on `onMessage` and `sendMessage` parameter `messageID`

### ISSUE THREAD

**Issue by ziloen** [zikaari/webext-bridge#60]
![Screenshot](https://i.imgur.com/r5EDYmm.png)

**Comment by zikaari** [comment]
I'm not understanding your issue, please describe with an example

**Comment by ziloen** [comment]
https://github.com/zikaari/webext-bridge/blob/320d2501599ed4e261801b0b65823b953633788a/src/internal/endpoint-runtime.ts#L16-L34

In the source code, `messageId` has a generic type `DataTypeKey`, but in the user's actual type file, the generic type of `messageId` changes to `string`, and when I expand the `ProtocolMap` type, I don't get a type hint at the `messageId`

```ts
declare module "webext-bridge" {
  export interface ProtocolMap {
    foo: { title: string }
    bar: ProtocolWithReturn<CustomDataType, CustomReturnType>;
  }
}

onMessage(messageId, ...)
//        ^ no type hint and accept any string
```

**Comment by ziloen** [comment]
Looks the same as #51, feel free to close.
