### ISSUE TITLE
Pratical exemple how to send message between my js and background-script.

### ISSUE THREAD

**Issue by capoia** [zikaari/webext-bridge#61]
Hello, I'm using a template that uses this package, but I'm having A LOT of difficulty communicating between the content-script and my application (in this case in vue).
I use this template: https://github.com/antfu/vitesse-webext

How would I send and receive content script messages inside my .vue files? Do I need to enable allowWindowMessaging? what would be the context of the .vue file or some .js file? because I saw that it has: devtools or content-script or background and window.
Sorry to post without reproduction, it's something I really can't even reproduce.

I am very grateful in advance, I will use it in my course conclusion work.

**Comment by zikaari** [comment]
Please post the issue in vitesse-webext repo since I don't have any experience with Vue
